# Site settings
title: Tim Korecky
email: trkorecky@gmail.com
description: "Personal portfolio website for game developer Tim Korecky. Check out what I've been working on!"
baseurl: ""
url: "http://timkorecky.com"
username: trkorecky
linkedinname: timothykorecky

# Build settings
markdown: kramdown
permalink: pretty