# Site settings
title: Tim Korecky
email: trkorecky@gmail.com
description: "Personal portfolio website for Tim Korecky. Game developer, technology enthusiast, alternative lifestyle explorer. Stop by to check out what I've been working on!"
baseurl: ""
url: "http://timkorecky.com"

# Build settings
markdown: kramdown
permalink: pretty
